### ISSUE TITLE
Share projects with other users

### ISSUE THREAD

**Issue by abainczyk** [LearnLib/alex#21]
To enable collaboration between users, it should be possible for multiple users to work with the same project.
Therefor, there should be several roles within a project:

**Owner**
- Can add users to the project as member by email or username
- Can make members owner of the project
- Can make owners member of the project
- Can remove owners and members from the project
- Can leave the project
- Each project can have multiple owners
- The last owner cannot leave the project

**Member**
- Cannot edit / delete the project, project environments, environment variables, base URLs
- Can leave the project

### Todos

- [x] Extend `Project` by 'owners' and 'members' property (list of `User`) 
    - The 'user' property should be removed    
- [x] Add view to manage users within a project
    - [x] Add route */project/{ID}/users*
    - [x] Add item to the sidebar that is only visible to owners
- [x] Add checks to the `ProjectDAO` so that members and owners are not able to edit / delete the project
- [x] Add checks to the `ProjectEnvironmentsDAO` so that members cannot create / edit / delete environments, base URLs and variables
- [x] On the view where all projects are displayed (*/projects*), separate by projects the user is owner of and projects the user is member of in two lists
    - [x] In the list of projects, a dropdown menu with the item *Leave project* should be displayed
        - Leaving the project requires confirmation with a confirm dialog
        - The last owner cannot leave the project
    - [x] Display a label *Owner* or *Member* to the corresponding projects
- [x] Members should not be able to access the environments view (*/projects/ID/environments*)
    - The *Environments* item in the sidebar should not be displayed

**Comment by abainczyk** [comment]
Implemented in 99ab0178f9fb8b4e88863f2e8f363a0fb0f7b7e3
