### ISSUE TITLE
Add support for usernames

### ISSUE THREAD

**Issue by abainczyk** [LearnLib/alex#44]
As a first step in the direction of supporting collaboration between users in ALEX, we want to extend the user model by a *username* property.

## Todos

- [x] update the user model to have the field 'username'
    - the username should be unique
- [x] create a component for the user registration form
    - it should be possible to specify a username in that form
- [x] on the start page, one should be able to switch between login and registration form via tabs
    - if the registration was successfull, the view should switch to the login form and insert the email and password combination
- [x] display the username in the top right corner in the header instead of the email prefix
- [x] when an admin creates / edits a new user via the user management view, he should be able to specify / edit the username 
- [x] extend the table in the user management view to display the username of a user
